- hosts: all
  vars:
    nginx_proxy_sites:
      - name: dedicated-pageflow.localhost
        port: 5100
      - name: hosted-pageflow.localhost
        port: 5101

    gh_repositories:
      - name: pageflow
      - name: pageflow-before-after
      - name: pageflow-chart
      - name: pageflow-embedded-video
      - name: pageflow-external-links
      - name: pageflow-internal-links
      - name: pageflow-outline-navigation-bar
      - name: pageflow-progress-navigation-bar
      - name: pageflow-public-i18n
      - name: pageflow-linkmap-page
      - name: pageflow-panorama
      - name: pageflow-parent-page-box
      - name: pageflow-new-pages-box
      - name: pageflow-text-page
      - name: pageflow-sitemap
      - name: pageflow-timeline-page
      - name: pageflow-vr
      - name: state_machine_job
      - name: cert_watch
      - name: activeadmin-searchable_select

  tasks:
#    - include: tasks/ssh.yml
#    - include: tasks/gems.yml

    - include_tasks: tasks/chrome.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/spotify.yml
    - include_tasks: tasks/gimp.yml

    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/emacs.yml
    - include_tasks: tasks/pass.yml

    - include_tasks: tasks/gh_repositories.yml

    - include_tasks: tasks/nginx.yml

  handlers:
    - include_tasks: handlers/ssh.yml
    - include_tasks: handlers/nginx.yml

  roles:
#    - { role: rvm.ruby,
#        rvm1_rubies: ['ruby-2.6.10'],
#        rvm1_install_flags: '--auto-dotfiles --user-install',
#        rvm1_install_path: '/home/tfischbach/.rvm',
#        rvm1_user: 'tfischbach',
#        rvm1_rvm_check_for_updates: false
#      }
#    - role: leonidas.nvm
#      nvm:
#        user: 'tfischbach'
#        version: HEAD
#        node_version: '12.18.0'
#
