- block:
  - name: "Add apt key"
    apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub

  - name: "Add apt repository"
    apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main'

  - name: "Install chrome"
    apt:
      name: google-chrome-stable

  become: yes
