- name: Install dnsmasq package
  apt: name=dnsmasq state=installed update_cache=yes
  become: yes

- name: Setup .localhost domains to resolve to localhost
  template: src=templates/dnsmasq_localhost_tld.j2
            dest=/etc/dnsmasq.d/localhost-tld
  become: yes
  notify: Restart dnsmasq