- block:
  - name: Rum lsb_release -cs
    command: 'lsb_release -cs'
    register: docker_lsb_release
    changed_when: False

  - name: Install packages to allow apt to use a repository over HTTPS
    apt: name={{item}} state=installed update_cache=yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

  - name: "Add docker apt key"
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: "Add docker apt repository"
    apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu {{docker_lsb_release}} stable'

  - name: "Install docker"
    apt: name=docker-ce state=installed update_cache=yes

  - name: "Add user to docker group"
    user:
      name: tfischbach
      groups: docker
      append: yes

  become: yes
  tags:
    - docker
