- name: "Checkout dotfiles repository"
  git: repo=git@github.com:tf/dotfiles dest=~/.dotfiles

- name: "Create symlinks for dotfiles"
  file: src=~/.dotfiles/.{{item}}
        dest=~/.{{item}}
        state=link
  with_items:
    - gitconfig
    - gitignore_global
    - profile.d
    - gemrc
    - ssh/config

- name: "Source .profile.d files"
  lineinfile: dest=~/{{item}}
              insertafter=EOF
              line="for conf in ~/.profile.d/*[^~]; do . $conf; done"
              state=present
  with_items:
    - .profile
    - .bashrc

