- block:
  - name: "Install emacs"
    apt:
      name: emacs

  - name: "Install emacs goodies"
    apt:
      name: emacs-goodies-el
  become: true
  tags:
  - emacs

- name: "Checkout emacs config"
  git: repo=git@github.com:tf/emacs-config
       dest=~/.emacs.d
