- block:
  - name: "Install emacs"
    apt:
      name: emacs
  become: true
  tags:
  - emacs

- name: "Checkout emacs config"
  git: repo=git@github.com:tf/prelude
       version=personal
       dest=~/.emacs.d
